# Application configuration file, used in read-only mode on initialization.
# Any parameters can be rewritten by command line.

# maximum run time of the application.
# Format is a time.Duration string (for example '1d8h15m30s')
# 0 means unlimited by time searching.
maxRunTime: 0s
# maximum number of requests to send to omdbapi.
# 0 means no limits for requests number on each founded entry.
maxRequests: 0
# regex pattern to apply to the plot of a film retrieved from OMDb.
plotFilter: ""
# OMDb service API calls configuration.
OMDb-param:
  # host of OMDb API service.
  OMDb-host: http://omdbapi.com
  # key for API requests to OMDb service.
  API-key: 124978f0
  # relative path to the inflated title.basics.tsv.gz file.
  filePath: data.tsv
  # number of threads to send queries to service.
  # 0 means to use all available logical CPUs.
  threads-num: 0
# default predefined search parameters that can be rewritten by command line.
search-param:
  # filter on titleType column.
  titleType: ""
  # filter on primaryTitle column.
  primaryTitle: ""
  # filter on originalTitle column.
  originalTitle: ""
  # filter on genre column.
  genre: ""
  # filter on startYear column.
  startYear: 0
  # filter on endYear column.
  endYear: 0
  # filter on runtimeMinutes column.
  runtimeMinutes: 0
  # filter on genres column.
  genres: ""
# parameters of result tables output.
print-param:
  # disables print of table with founded entries in local DB, print only its number.
  no-basic-table: false
  # list of columns with its description for basic table output.
  basic-table-info:
    # draw border around of table
    border: false
    # draw grid inside of table
    grid: true
    # each element of list contains 3 fields: value, limit and margin.
    # limit points to maximum length of fields, its cuts if exceeds.
    # margin points to number of spaces on left and right, and can be 0.
    # value can be one of the followed:
    #   IMDB_ID (or tconst), titleType, Title (or primaryTitle),
    #   originalTitle, isAdult, Year (or startYear), endYear,
    #   Length (or runtimeMinutes), Genres (genres).
    header:
    - value: IMDB_ID
      limit: 9
      margin: 1
    - value: Title
      limit: 32
      margin: 1
    - value: Year
      limit: 4
      margin: 1
    - value: Genres
      limit: 0
      margin: 1
  # list of columns with its description for OMDb table output.
  OMDb-table-info:
    # draw border around of table
    border: true
    # draw grid inside of table
    grid: true
    # each element of list contains 3 fields: value, limit and margin.
    # limit points to maximum length of fields, its cuts if exceeds.
    # margin points to number of spaces on left and right, and can be 0.
    # value can be one of the followed:
    #   Title, Year, Rated, Released, Runtime, Genre, Director, Writer,
    #   Actors, Plot, Language, Country, Awards, Poster, Metascore,
    #   ImdbRating (imdbRating), ImdbVotes (imdbVotes), ImdbID (imdbID,
    #   IMDB_ID, tconst), Type, DVD, BoxOffice, Production, Website, Response.
    header:
    - value: IMDB_ID
      limit: 9
      margin: 1
    - value: Title
      limit: 32
      margin: 1
    - value: Plot
      limit: 120
      margin: 1
  # disables print of table with full description provided by OMDb service.
  no-OMDb-table: false
  # maximum length of title in table.
  title-len: 32
  # maximum length of plot in table.
  plot-len: 120
